#cloud-config
# Simple cloud-init for AAP host - just basic prep, disk expansion handled by Ansible

packages:
  - lvm2
  - xfsprogs

runcmd:
  # Just ensure basic LVM tools are available
  # Disk expansion will be handled by Ansible post-provisioning
  - echo "AAP host cloud-init complete - disk expansion will be handled by Ansible"
  - lsblk
  - df -h