#cloud-config
# Prepares RHEL jump host with Ansible tools

hostname: jump-host
fqdn: jump-host.internal.demo
users:
  - name: rheluser
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]

runcmd:
  - echo "Installing Python and Ansible tools..."
  - dnf upgrade -y
  - dnf install -y ansible-core
  - echo "✅ Jump host cloud-init complete"
