# ─────────────────────────────────────────────────────────────
# Defaults ▸ run_aap_installer_from_jump
# ─────────────────────────────────────────────────────────────
aap_bundle_path: "/var/tmp/aap-setup-2.5.tar.gz" # already on jump
aap_extract_root: "/opt"  # AAP will be extracted to /opt (expanded by disk resize)
aap_registry_url: registry.redhat.io

# provided by vault / CI  ───────────────────────────────────
aap_admin_password: "{{ omit }}" # asserted in tasks
aap_pg_password: "{{ omit }}"
