# group_vars/aap.yml
# Variables for installing Ansible Automation Platform (AAP) on the AAP VM

# Path to the AAP installer tarball located on the Jump Host.
# This file will be copied by Ansible to the AAP VM during the playbook run.
aap_installer_archive: "/var/tmp/Ansible Automation Platform 2.5 Setup.tar.gz"

# Destination directory on the AAP VM where the installer will be copied and unpacked.
# The setup process will be executed from this location.
aap_target_path: "/opt/ansible-automation-platform"

# Name of the inventory file to be used by the AAP installer (within aap_target_path).
# This should define localhost and any required installation settings.
aap_inventory_file: "inventory.yml"
