---
- name: Clone Ansible Demo Repository onto Jump Host
  hosts: jump
  gather_facts: false
  become: true

  vars:
    git_repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    repo_version: "main"
    repo_clone_path: "/home/rheluser/{{ git_repo_url | basename | regex_replace('\\.git$', '') }}"

  tasks:

    # ─────────────────────────────────────────────────────
    # Step 1: Ensure Git is Available
    # ─────────────────────────────────────────────────────
    - name: Ensure Git is installed on the Jump Host
      package:
        name: git
        state: present

    # ─────────────────────────────────────────────────────
    # Step 2: Check if repo already exists and is a Git repo
    # ─────────────────────────────────────────────────────
    - name: Check if .git/config exists in clone path
      stat:
        path: "{{ repo_clone_path }}/.git/config"
      register: git_config_check

    # ─────────────────────────────────────────────────────
    # Step 3: Clone repo if not already present
    # ─────────────────────────────────────────────────────
    - name: Clone Git repository (only if not already cloned)
      become: true
      become_user: rheluser
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
        update: false
      when: not git_config_check.stat.exists

    # ─────────────────────────────────────────────────────
    # Step 4: Pull latest changes if repo already exists
    # ─────────────────────────────────────────────────────
    - name: Pull latest changes from remote
      become: true
      become_user: rheluser
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
        update: true
      when: git_config_check.stat.exists

    # ─────────────────────────────────────────────────────
    # Step 5: Confirm Repo Path
    # ─────────────────────────────────────────────────────
    - name: Confirm Git repository is available on Jump Host
      debug:
        msg: "Repository is now available at {{ repo_clone_path }}"
