---
- name: Clone Ansible Demo Repository onto Jump Host
  hosts: jump
  gather_facts: false
  become: true

  vars:
    git_repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    repo_version: "main"
    repo_clone_path: "/home/rheluser/{{ git_repo_url | basename | regex_replace('\\.git$', '') }}"

  tasks:

    # ─────────────────────────────────────────────────────
    # Step 1: Ensure Git is Available
    # ─────────────────────────────────────────────────────
    - name: Ensure Git is installed on the Jump Host
      package:
        name: git
        state: present

    # ─────────────────────────────────────────────────────
    # Step 2: Ensure Git repository is present and up-to-date
    # ─────────────────────────────────────────────────────
    - name: Clone or pull Git repository
      become: true
      become_user: rheluser
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
        update: true  # This is the key: it handles both cloning and pulling
        force: yes    # Add force: yes to ensure it can overwrite if the directory is not a proper git repo.
                      # Use with caution, but it helps recover from corrupted states.

    # ─────────────────────────────────────────────────────
    # Step 3: Confirm Repo Path
    # ─────────────────────────────────────────────────────
    - name: Confirm Git repository is available on Jump Host
      debug:
        msg: "Repository is now available at {{ repo_clone_path }}"
