---
- name: Clone or update Git repository on Jump Host
  hosts: jump
  gather_facts: false

  vars:
    git_repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    repo_version: "main"
    repo_clone_path: "/home/rheluser/{{ git_repo_url | basename | regex_replace('\\.git$', '') }}"

  tasks:

    # ─────────────────────────────────────────────────────
    # Step 1: Ensure Git is Available
    # ─────────────────────────────────────────────────────
    - name: Ensure Git is installed on the Jump Host
      become: true
      package:
        name: git
        state: present

    # ─────────────────────────────────────────────────────
    # Step 2: Check if repository already exists
    # ─────────────────────────────────────────────────────
    - name: Check if Git repository already exists
      ansible.builtin.stat:
        path: "{{ repo_clone_path }}/.git"
      register: repo_exists

    # ─────────────────────────────────────────────────────
    # Step 3a: Clone repository if it doesn't exist
    # ─────────────────────────────────────────────────────
    - name: Clone Git repository (if not present)
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
        force: true
      become: true
      become_user: rheluser
      when: not repo_exists.stat.exists

    # ─────────────────────────────────────────────────────
    # Step 3b: Pull latest changes if it already exists
    # ─────────────────────────────────────────────────────
    - name: Pull latest changes from Git repository
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
        update: yes
        force: false
      become: true
      become_user: rheluser
      when: repo_exists.stat.exists

    # ─────────────────────────────────────────────────────
    # Step 4: Confirm repository is available
    # ─────────────────────────────────────────────────────
    - name: Confirm Git repository is available on Jump Host
      ansible.builtin.debug:
        msg: "Repository is now available at {{ repo_clone_path }}"
