- name: Clone Ansible Demo Repository onto Jump Host
  hosts: jump
  gather_facts: false

  vars:
    git_repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    repo_version: "main"
    repo_clone_path: "/home/rheluser/{{ git_repo_url | basename | regex_replace('\\.git$', '') }}"

  tasks:

    # ──────────────────────────────────────────────
    # Step 1: Ensure Git is Installed
    # ──────────────────────────────────────────────
    - name: Ensure Git is installed on the Jump Host
      become: true
      package:
        name: git
        state: present

    # ──────────────────────────────────────────────
    # Step 2: Check if repository already exists
    # ──────────────────────────────────────────────
    - name: Check if repository already exists
      become: true
      become_user: rheluser
      stat:
        path: "{{ repo_clone_path }}/.git"
      register: git_repo_status

    # ──────────────────────────────────────────────
    # Step 3a: Clone repository if it doesn't exist
    # ──────────────────────────────────────────────
    - name: Clone repository if it doesn't exist
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
      become: true
      become_user: rheluser
      when: not git_repo_status.stat.exists

    # ──────────────────────────────────────────────
    # Step 3b: Pull latest changes if repo already exists
    # ──────────────────────────────────────────────
    - name: Pull latest changes from repository
      become: true
      become_user: rheluser
      shell: |
        git pull origin {{ repo_version }}
      args:
        chdir: "{{ repo_clone_path }}"
      when: git_repo_status.stat.exists

    # ──────────────────────────────────────────────
    # Step 4: Confirm Git repository is available
    # ──────────────────────────────────────────────
    - name: Confirm Git repository is available on Jump Host
      debug:
        msg: "Repository is now available at {{ repo_clone_path }}"
