---
- name: Clone Ansible Demo Repository onto Jump Host
  hosts: jump
  gather_facts: false

  vars:
    git_repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    repo_version: "main"
    repo_clone_path: "/home/rheluser/{{ git_repo_url | basename | regex_replace('\\.git$', '') }}"

  tasks:

    # ─────────────────────────────────────────────────────
    # Step 1: Ensure Git is Available
    # ─────────────────────────────────────────────────────
    - name: Ensure Git is installed on the Jump Host
      become: true
      package:
        name: git
        state: present

    # ─────────────────────────────────────────────────────
    # Step 2: Clone or Update Repository
    # ─────────────────────────────────────────────────────
    - name: Clone or update Git repository on Jump Host
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
        update: yes
        force: true

    # ─────────────────────────────────────────────────────
    # Step 3: Confirm Success
    # ─────────────────────────────────────────────────────
    - name: Confirm Git repository is available on Jump Host
      debug:
        msg: "Repository is now available at {{ repo_clone_path }}"
