---
- name: Clone Ansible Demo Repository onto Jump Host
  hosts: jump
  gather_facts: false

  vars:
    git_repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    repo_version: "main"
    repo_clone_path: "/home/rheluser/{{ git_repo_url | basename | regex_replace('\\.git$', '') }}"

  tasks:

    # ──────────────────────────────────────────────
    # Step 1: Ensure Git is Installed
    # ──────────────────────────────────────────────
    - name: Ensure Git is installed on the Jump Host
      become: true
      package:
        name: git
        state: present

    # ──────────────────────────────────────────────
    # Step 2: Check if repo already exists
    # ──────────────────────────────────────────────
    - name: Check if repository already exists
      ansible.builtin.stat:
        path: "{{ repo_clone_path }}/.git"
      register: repo_exists

    # ──────────────────────────────────────────────
    # Step 3: Clone or update repository
    # ──────────────────────────────────────────────
    - name: Clone or update Git repository on Jump Host
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
        update: yes
        force: no
      become: true
      become_user: rheluser

    # ──────────────────────────────────────────────
    # Step 4: Confirm Git repository is available
    # ──────────────────────────────────────────────
    - name: Confirm Git repository is available on Jump Host
      debug:
        msg: "Repository is now available at {{ repo_clone_path }}"
