---
- name: Clone Ansible Demo Repository onto Jump Host
  hosts: jump
  become: true
  gather_facts: false

  vars:
    git_repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    repo_version: "main"
    repo_clone_path: "/home/rheluser/{{ git_repo_url | basename | regex_replace('\\.git$', '') }}"

  tasks:

    # ─────────────────────────────────────────────────────
    # Step 1: Ensure Git is Available
    # ─────────────────────────────────────────────────────
    - name: Ensure Git is installed on the Jump Host
      package:
        name: git
        state: present

    # ─────────────────────────────────────────────────────
    # Step 2: Check if Repo Already Exists
    # ─────────────────────────────────────────────────────
    - name: Check if Git repository already exists
      stat:
        path: "{{ repo_clone_path }}/.git"
      register: repo_exists

    # ─────────────────────────────────────────────────────
    # Step 3: Clone Repo if Not Present
    # ─────────────────────────────────────────────────────
    - name: Clone Git repository (if not present)
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_clone_path }}"
        version: "{{ repo_version }}"
        update: no
      become_user: rheluser
      when: not repo_exists.stat.exists

    # ─────────────────────────────────────────────────────
    # Step 4: Confirm Repository Path
    # ─────────────────────────────────────────────────────
    - name: Confirm Git repository is available on Jump Host
      debug:
        msg: "Repository is now available at {{ repo_clone_path }}"
