# ─────────────────────────────────────────────────────────────
# Playbook: configure-jump-host.yml
# Purpose: Prepare Jump Host for automation by installing prereqs
# ─────────────────────────────────────────────────────────────

- name: Configure Jump Host
  hosts: jump
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    # ─────────────────────────────────────────────────────────
    # Step 1: Update all system packages
    # ─────────────────────────────────────────────────────────
    - name: Update all packages on the Jump Host
      dnf:
        name: '*'
        state: latest
        update_cache: true

    # ─────────────────────────────────────────────────────────
    # Step 2: Ensure Git is installed
    # ─────────────────────────────────────────────────────────
    - name: Install Git if not already present
      dnf:
        name: git
        state: present

    # ─────────────────────────────────────────────────────────
    # Step 3: Ensure rsync is installed
    # ─────────────────────────────────────────────────────────
    - name: Install rsync if not already present
      dnf:
        name: rsync
        state: present

    # ─────────────────────────────────────────────────────────
    # Step 4: Ensure Python pip is installed
    # ─────────────────────────────────────────────────────────
    - name: Install pip for Python 3
      dnf:
        name: python3-pip
        state: present

    # ─────────────────────────────────────────────────────────
    # Step 5: Confirm Jump Host configuration is complete
    # ─────────────────────────────────────────────────────────
    - name: Confirm Jump Host prereqs are installed
      debug:
        msg: "Jump Host is ready: system updated and required tools installed."
