- name: Configure Jump Host
  hosts: jump
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update all packages on the jump host
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
      tags: skip_ansible_lint

    - name: Ensure base packages are present
      ansible.builtin.package:
        name:
          - git
          - rsync
          - python3-pip
          - python3.11
          - python3.11-pip
          - tar
          - unzip
          - podman
        state: present

    - name: Try to install ruamel.yaml via dnf
      ansible.builtin.package:
        name: python3-ruamel-yaml
        state: present
      register: dnf_ruamel
      failed_when: false

    - name: Install ruamel.yaml via pip if dnf not available
      when: dnf_ruamel is failed or (dnf_ruamel is defined and dnf_ruamel.rc | default(1) != 0)
      ansible.builtin.pip:
        name: ruamel.yaml
        state: present
        executable: /usr/bin/pip3

    - name: Verify ruamel.yaml present
      ansible.builtin.command: >
        python3 -c "import importlib.util;
                    print('ruamel.yaml found:',
                    bool(importlib.util.find_spec('ruamel.yaml')))"
      register: ruamel_check
      changed_when: false
      failed_when: false

    - name: Show ruamel.yaml presence result
      ansible.builtin.debug:
        msg: "{{ ruamel_check.stdout.strip() }}"

    - name: Check current Ansible version
      ansible.builtin.command: ~/.local/bin/ansible --version
      register: ansible_ver_check
      failed_when: false
      changed_when: false
      become: false

    - name: Install Ansible 2.16.x under user context if not present
      become: false
      ansible.builtin.shell: /usr/bin/python3.11 -m pip install --user "ansible>=2.16,<2.17"
      args:
        executable: /bin/bash
      when: "'2.16.' not in ansible_ver_check.stdout"

    - name: Ensure ~/.bashrc has updated PATH for local bin
      ansible.builtin.lineinfile:
        path: /home/rheluser/.bashrc
        line: 'export PATH="$HOME/.local/bin:$PATH"'
        state: present
        create: yes
        mode: '0644'

    - name: Ensure ANSIBLE_CONFIG is set in ~/.bashrc
      ansible.builtin.lineinfile:
        path: /home/rheluser/.bashrc
        line: 'export ANSIBLE_CONFIG="/home/rheluser/ansible-cert-renewal-demo/ansible/ansible.cfg"'
        state: present
        create: yes
        mode: '0644'

    - name: Jump host ready
      ansible.builtin.debug:
        msg: "Jump host packages, Ansible 2.16.x, and Python dependencies are installed."
