---
# ─────────────────────────────────────────────────────────────
# Playbook: configure-jump-host.yml
# Purpose : Prepare the jump host for later automation
# ─────────────────────────────────────────────────────────────

- name: Configure Jump Host
  hosts: jump
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    # ── System update ───────────────────────────────────────
    - name: Update all packages on the jump host
      dnf:
        name: '*'
        state: latest
        update_cache: true

    # ── Core tools ───────────────────────────────────────────
    - name: Ensure base packages are present
      package:
        name:
          - git
          - rsync
          - python3-pip
          - tar
          - unzip
          - podman
        state: present

    # ── ruamel.yaml for YAML callback ───────────────────────
    - name: Try to install ruamel.yaml via dnf
      package:
        name: python3-ruamel-yaml
        state: present
      register: dnf_ruamel
      failed_when: false

    - name: Install ruamel.yaml via pip if dnf not available
      pip:
        name: ruamel.yaml
        state: present
        executable: /usr/bin/pip3
      when: dnf_ruamel is failed or
            (dnf_ruamel is defined and dnf_ruamel.rc|default(1) != 0)

    - name: Verify ruamel.yaml present
      command: >
        python -c "import importlib.util,sys;
                   print('ruamel.yaml found:',
                         bool(importlib.util.find_spec('ruamel.yaml')))"
      register: ruamel_check
      changed_when: false
      failed_when: false

    - name: Show ruamel.yaml presence result
      debug:
        msg: "{{ ruamel_check.stdout.strip() }}"

    # ── Final message ───────────────────────────────────────
    - name: Jump host ready
      debug:
        msg: "Jump host packages and Python dependencies are installed."
