---
# ─────────────────────────────────────────────────────────────
# Playbook: copy-private-key.yml
# Purpose : Injects SSH private key and sets up SSH client config
#           on the jump host for inter-VM communication.
# ─────────────────────────────────────────────────────────────
- name: Inject SSH Private Key to Jump Host for Inter-VM Communication
  hosts: jump
  gather_facts: true # Gather facts to ensure 'ansible_user_dir' is available if not defined globally
  vars:
    # Path to the private key on the local (laptop) control node
    private_key_path: "{{ private_key_path }}"
    # Expected user home directory on the jump host
    ansible_user_dir: /home/rheluser
    # Destination path for the private key on the jump host
    jump_host_key_dest: "{{ ansible_user_dir }}/.ssh/ansible-demo-key"
    # IP address of the AAP host (to be scanned from the jump host)
    aap_host_ip: "{{ aap_host_ip | default('10.0.1.12') }}" # Use passed var or default

  tasks:
    # ─────────────────────────────────────────────────────
    # Task 0.1 – Ensure ~/.ssh directory exists on jump host
    # ─────────────────────────────────────────────────────
    - name: Ensure ~/.ssh directory exists on jump host
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    # ─────────────────────────────────────────────────────
    # Task 0.2 – Copy private SSH key to the jump host
    # ─────────────────────────────────────────────────────
    - name: Copy private SSH key to the jump host
      ansible.builtin.copy:
        src: "{{ private_key_path }}" # Source is on laptop
        dest: "{{ jump_host_key_dest }}" # Destination is on jump host
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    # ─────────────────────────────────────────────────────
    # Task 0.3 – Configure SSH client on the jump host
    #           (for internal VM communication)
    # ─────────────────────────────────────────────────────
    - name: Configure SSH client on the jump host
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.ssh/config"
        create: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        block: |
          Host 10.0.1.*
            User rheluser
            IdentityFile ~/.ssh/ansible-demo-key
            IdentitiesOnly yes
            # These are for older SSH servers that might require specific algorithms
            PubkeyAcceptedAlgorithms +ssh-rsa,ssh-dss,rsa-sha2-256,rsa-sha2-512,ssh-ed25519,ecdsa-sha2-nistp256,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com
            HostKeyAlgorithms +ssh-rsa,ssh-dss,rsa-sha2-256,rsa-sha2-512,ssh-ed25519,ecdsa-sha2-nistp256,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com
            KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
            Ciphers +aes128-cbc,aes192-cbc,aes256-cbc
            ConnectTimeout 10
            # Removed StrictHostKeyChecking no and UserKnownHostsFile /dev/null
            # as host keys will be managed via known_hosts module.

    # ─────────────────────────────────────────────────────
    # Task 0.4 – Scan SSH host key for AAP host from Jump Host
    #            (Delegate to ensure scan happens from jump host)
    # ─────────────────────────────────────────────────────
    - name: Scan SSH host key for AAP host from Jump Host
      ansible.builtin.command: "ssh-keyscan -p 22 -H {{ aap_host_ip }}"
      register: aap_keyscan_result
      delegate_to: jump-host # Crucial: This command runs on the jump-host
      changed_when: false # This task won't change state itself

    # ─────────────────────────────────────────────────────
    # Task 0.5 – Add scanned key to ~/.ssh/known_hosts on jump host
    #            (Delegate to ensure update happens on jump host)
    # ─────────────────────────────────────────────────────
    - name: Add scanned key to ~/.ssh/known_hosts on jump host
      ansible.builtin.known_hosts:
        name: "{{ aap_host_ip }}"
        key: "{{ aap_keyscan_result.stdout }}"
        state: present
        hash_host: true # Recommended for security
        path: "{{ ansible_user_dir }}/.ssh/known_hosts"
      delegate_to: jump-host # Crucial: This task operates on the jump-host
      when: aap_keyscan_result.stdout # Only add if keyscan succeeded

    # ─────────────────────────────────────────────────────
    # Task 0.6 – Confirm SSH setup complete on jump host
    # ─────────────────────────────────────────────────────
    - name: Confirm SSH key and known_hosts configured on jump host
      ansible.builtin.debug:
        msg: "SSH key copied to {{ jump_host_key_dest }} and AAP host key ({{ aap_host_ip }}) added to known_hosts on jump host."
