---
- name: Inject SSH Private Key to Jump Host for Inter-VM Communication
  hosts: jump
  gather_facts: false

  vars:
    private_key_path: ""
    remote_key_dest: "/home/rheluser/.ssh/ansible-demo-key"

  tasks:

    # ─────────────────────────────────────────────────────────────
    # Step 1: Validate Private Key Exists Locally
    # ─────────────────────────────────────────────────────────────
    - name: Check if the private key exists locally on the Ansible control machine
      ansible.builtin.stat:
        path: "{{ private_key_path }}"
      delegate_to: localhost
      register: local_private_key_check

    - name: Fail if the private key is missing locally
      ansible.builtin.fail:
        msg: "❌ The private SSH key is not found at '{{ private_key_path }}'. Please ensure it exists."
      when: not local_private_key_check.stat.exists

    # ─────────────────────────────────────────────────────────────
    # Step 2: Ensure .ssh Directory Exists and Has Correct Permissions on Jump Host
    # ─────────────────────────────────────────────────────────────
    - name: Create .ssh directory on the Jump Host if it doesn't exist
      ansible.builtin.file:
        path: "/home/rheluser/.ssh"
        state: directory
        mode: '0700'
        owner: rheluser
        group: rheluser
      become: false

    # ─────────────────────────────────────────────────────────────
    # Step 3: Copy Private Key to Jump Host
    # ─────────────────────────────────────────────────────────────
    - name: Copy the private SSH key to the Jump Host
      ansible.builtin.copy:
        src: "{{ private_key_path }}"
        dest: "{{ remote_key_dest }}"
        mode: '0600'
        owner: rheluser
        group: rheluser
      become: false

    - name: Confirm successful private key injection
      ansible.builtin.debug:
        msg: "Private SSH key successfully copied to {{ remote_key_dest }} on the Jump Host."

    # ─────────────────────────────────────────────────────────────
    # Step 4: Get SSH host keys for internal Linux VMs
    # ─────────────────────────────────────────────────────────────
    - name: Get SSH host key for internal VMs
      ansible.builtin.command: "ssh-keyscan -p 22 -H {{ hostvars[item].ansible_host }}"
      register: ssh_keyscan_results # Register ALL results from the loop
      delegate_to: jump-host
      become: false
      changed_when: false
      loop: "{{ groups['aap'] + groups['rhel_web'] }}"
      when:
        - (groups['aap'] is defined and groups['aap'] | length > 0) or
          (groups['rhel_web'] is defined and groups['rhel_web'] | length > 0)

    - name: Add host key to Jump Host's known_hosts file
      ansible.builtin.known_hosts:
        name: "{{ item.item }}" # The original item (host name/alias) from the outer loop
        key: "{{ item.stdout }}" # Access stdout from the registered result of the 'command' task
        state: present
        hash_host: true
      delegate_to: jump-host
      become: false
      # Loop over the results of the *previous* task's loop
      loop: "{{ ssh_keyscan_results.results }}"
      # Only run if the previous task actually registered results
      when: ssh_keyscan_results is defined and ssh_keyscan_results.results | length > 0
