---
- name: Inject SSH Private Key to Jump Host for Inter-VM Communication
  hosts: jump # This playbook explicitly targets the jump host
  gather_facts: false # No need to gather facts for simple file operations

  vars:
    # ───── Local path to the private SSH key being copied ─────
    # This variable is expected to be passed from the calling playbook or script.
    # Example: ansible-playbook ... -e "private_key_path=/home/user/.ssh/ansible-demo-key"
    private_key_path: "" # Will be set by the caller (from build-demo.sh)

    # ───── Target path on the Jump Host for the private key ─────
    remote_key_dest: "/home/rheluser/.ssh/ansible-demo-key"

  tasks:

    # ─────────────────────────────────────────────────────────────
    # Step 1: Validate Private Key Exists Locally
    # ─────────────────────────────────────────────────────────────

    - name: Check if the private key exists locally on the Ansible control machine
      ansible.builtin.stat:
        path: "{{ private_key_path }}"
      delegate_to: localhost # Run this task on the machine executing Ansible
      register: local_private_key_check

    - name: Fail if the private key is missing locally
      ansible.builtin.fail:
        msg: "❌ The private SSH key is not found at '{{ private_key_path }}'. Please ensure it exists."
      when: not local_private_key_check.stat.exists

    # ─────────────────────────────────────────────────────────────
    # Step 2: Ensure .ssh Directory Exists and Has Correct Permissions on Jump Host
    # ─────────────────────────────────────────────────────────────

    - name: Create .ssh directory on the Jump Host if it doesn't exist
      ansible.builtin.file:
        path: "/home/rheluser/.ssh"
        state: directory
        mode: '0700' # Essential: secure permissions for SSH directories
        owner: rheluser
        group: rheluser
      become: false # Operate as the 'rheluser' for their home directory

    # ─────────────────────────────────────────────────────────────
    # Step 3: Copy Private Key to Jump Host
    # ─────────────────────────────────────────────────────────────

    - name: Copy the private SSH key to the Jump Host
      ansible.builtin.copy:
        src: "{{ private_key_path }}"
        dest: "{{ remote_key_dest }}"
        mode: '0600' # Essential: secure permissions for private keys
        owner: rheluser
        group: rheluser
      become: false # Copy as the 'rheluser'

    - name: Confirm successful private key injection
      ansible.builtin.debug:
        msg: "✅ Private SSH key successfully copied to {{ remote_key_dest }} on the Jump Host."

    # ─────────────────────────────────────────────────────────────
    # Step 4: Get SSH host keys for internal Linux VMs
    # ─────────────────────────────────────────────────────────────
    - name: Get SSH host key for internal VMs
      ansible.builtin.command: "ssh-keyscan -p 22 -H {{ hostvars[item].ansible_host }}"
      register: ssh_keyscan_results # Register ALL results from the loop
      delegate_to: jump-host # Run ssh-keyscan from the jump host itself
      become: false # Run as rheluser
      changed_when: false # This command doesn't change system state
      loop: "{{ groups['aap'] + groups['rhel_web'] }}" # Loop over the hosts you want to scan
      when:
        - (groups['aap'] is defined and groups['aap'] | length > 0) or
          (groups['rhel_web'] is defined and groups['rhel_web'] | length > 0)


    - name: Add host key to Jump Host's known_hosts file
      ansible.builtin.known_hosts:
        name: "{{ item.item }}" # The original item (host name/alias) from the outer loop
        key: "{{ item.stdout }}" # Access stdout from the registered result of the 'command' task
        state: present
        hash_host: true
      delegate_to: jump-host # Apply this on the jump host
      become: false # Operate as rheluser
      loop: "{{ ssh_keyscan_results.results }}" # Loop over the results of the *previous* task's loop
      when: ssh_keyscan_results is defined and ssh_keyscan_results.results | length > 0
