---
- name: Inject SSH Private Key to Jump Host for Inter-VM Communication
  hosts: jump
  gather_facts: false

  vars:
    # Where the key lives on your Ansible control node
    private_key_path: "{{ private_key_path | default('~/.ssh/ansible-demo-key') }}"
    # Where it will be placed on the jump host
    remote_key_dest: "/home/rheluser/.ssh/ansible-demo-key"

  tasks:
  # ─────────────────────────────────────────────────────────────
  # Step 1 ▸ Validate the key exists locally (runs on control node)
  # ─────────────────────────────────────────────────────────────
  - name: Check if the private key exists locally
    ansible.builtin.stat:
      path: "{{ private_key_path }}"
    delegate_to: localhost
    run_once: true
    register: local_private_key_check

  - name: Fail if the private key is missing
    ansible.builtin.fail:
      msg: "Private SSH key not found at '{{ private_key_path }}'."
    when: not local_private_key_check.stat.exists
    run_once: true

  # ─────────────────────────────────────────────────────────────
  # Step 2 ▸ Ensure ~/.ssh exists on the jump host
  # ─────────────────────────────────────────────────────────────
  - name: Create ~/.ssh on the jump host
    ansible.builtin.file:
      path: "/home/rheluser/.ssh"
      state: directory
      mode: '0700'
      owner: rheluser
      group: rheluser

  # ─────────────────────────────────────────────────────────────
  # Step 3 ▸ Copy the private key to the jump host
  # ─────────────────────────────────────────────────────────────
  - name: Copy private SSH key to the jump host
    ansible.builtin.copy:
      src: "{{ private_key_path }}"
      dest: "{{ remote_key_dest }}"
      mode: '0600'
      owner: rheluser
      group: rheluser

  - name: Confirm private key was copied
    ansible.builtin.debug:
      msg: "Private key copied to {{ remote_key_dest }}"

  # ─────────────────────────────────────────────────────────────
  # Step 4 ▸ NEW – configure OpenSSH on the jump host to use the key
  # ─────────────────────────────────────────────────────────────
  - name: Configure SSH client on the jump host
    ansible.builtin.blockinfile:
      path: "/home/rheluser/.ssh/config"
      create: yes
      owner: rheluser
      group: rheluser
      mode: '0600'
      block: |
        Host 10.0.1.*                # adjust subnet/alias as needed
          User            rheluser
          IdentityFile    ~/.ssh/ansible-demo-key
          IdentitiesOnly  yes

  # (Optional) fix SELinux context if enforcing
  - name: Restore SELinux context on ~/.ssh (optional)
    ansible.builtin.command: /sbin/restorecon -Rv /home/rheluser/.ssh/
    when: ansible_selinux.status is defined and ansible_selinux.status == "enabled"
    changed_when: false

  # ─────────────────────────────────────────────────────────────
  # Step 5 ▸ Fetch SSH host keys for internal VMs
  # ─────────────────────────────────────────────────────────────
  - name: Scan SSH host keys for internal VMs
    ansible.builtin.command: "ssh-keyscan -p 22 -H {{ hostvars[item].ansible_host }}"
    register: _ssh_keyscan_result
    delegate_to: "{{ groups['jump'][0] }}"
    changed_when: false
    ignore_errors: true
    loop: "{{ (groups['aap'] | default([])) + (groups['rhel_web'] | default([])) }}"
    when:
      - _ssh_keyscan_result is not defined  # guard against first run
      - hostvars[item].ansible_host is defined

  # ─────────────────────────────────────────────────────────────
  # Step 6 ▸ Add those keys to known_hosts on the jump host
  # ─────────────────────────────────────────────────────────────
  - name: Add scanned keys to ~/.ssh/known_hosts
    ansible.builtin.known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
      state: present
      hash_host: true
    loop: >-
      {{ _ssh_keyscan_result.results
         | selectattr('rc','defined')
         | selectattr('rc','equalto',0)
         | selectattr('stdout','defined')
         | selectattr('stdout','truthy')
         | list }}
    delegate_to: "{{ groups['jump'][0] }}"

  # ─────────────────────────────────────────────────────────────
  # Step 7 ▸ OPTIONAL – test connectivity from the jump host
  # ─────────────────────────────────────────────────────────────
  - name: Test SSH connectivity from jump host to internal VMs
    ansible.builtin.shell: >
      ssh -o ConnectTimeout=5
          -o StrictHostKeyChecking=no
          rheluser@{{ hostvars[item].ansible_host }} hostname
    register: ssh_test_result
    delegate_to: "{{ groups['jump'][0] }}"
    ignore_errors: true
    changed_when: false
    loop: "{{ (groups['aap'] | default([])) + (groups['rhel_web'] | default([])) }}"

  - name: Display SSH test results
    ansible.builtin.debug:
      msg: "SSH to {{ item.item }} → {{ item.stdout | default('FAILED') }} (rc={{ item.rc }})"
    loop: "{{ ssh_test_result.results }}"
    when: ssh_test_result.results is defined
