---
- name: Inject SSH Private Key to Jump Host for Inter-VM Communication
  hosts: jump # This playbook specifically targets the jump host
  gather_facts: false # No need to gather facts for simple file operations

  vars:
    # ───── Local path to the private SSH key being copied ─────
    # This variable is expected to be passed from the calling playbook or script.
    # Example: ansible-playbook ... -e "private_key_path=/home/user/.ssh/ansible-demo-key"
    private_key_path: "" # Will be set by the caller

    # ───── Target path on the Jump Host for the private key ─────
    remote_key_dest: "/home/rheluser/.ssh/ansible-demo-key"

  tasks:

    # ─────────────────────────────────────────────────────────────
    # Step 1: Validate Private Key Exists Locally
    # ─────────────────────────────────────────────────────────────

    - name: Check if the private key exists locally on the Ansible control machine
      ansible.builtin.stat:
        path: "{{ private_key_path }}"
      delegate_to: localhost # Run this task on the machine executing Ansible
      register: local_private_key_check

    - name: Fail if the private key is missing locally
      ansible.builtin.fail:
        msg: "❌ The private SSH key is not found at '{{ private_key_path }}'. Please ensure it exists."
      when: not local_private_key_check.stat.exists

    # ─────────────────────────────────────────────────────────────
    # Step 2: Ensure .ssh Directory Exists and Has Correct Permissions on Jump Host
    # ─────────────────────────────────────────────────────────────

    - name: Create .ssh directory on the Jump Host if it doesn't exist
      ansible.builtin.file:
        path: "/home/rheluser/.ssh"
        state: directory
        mode: '0700' # Essential: secure permissions for SSH directories
        owner: rheluser
        group: rheluser
      become: false # Operate as the 'rheluser' for their home directory

    # ─────────────────────────────────────────────────────────────
    # Step 3: Copy Private Key to Jump Host
    # ─────────────────────────────────────────────────────────────

    - name: Copy the private SSH key to the Jump Host
      ansible.builtin.copy:
        src: "{{ private_key_path }}"
        dest: "{{ remote_key_dest }}"
        mode: '0600' # Essential: secure permissions for private keys
        owner: rheluser
        group: rheluser
      become: false # Copy as the 'rheluser'

    - name: Confirm successful private key injection
      ansible.builtin.debug:
        msg: "Private SSH key successfully copied to {{ remote_key_dest }} on the Jump Host."

    # ─────────────────────────────────────────────────────────────
    # Step 4: Add Internal VMs to Jump Host's known_hosts (Optional but Recommended)
    # ─────────────────────────────────────────────────────────────

    - name: Add internal Linux VMs to the Jump Host's known_hosts file
      ansible.builtin.known_hosts:
        name: "{{ hostvars[item].ansible_host }}"
        state: present
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + hostvars[item].ansible_host) }}"
        hash_host: true # Hashes the hostnames for privacy/security
      loop: "{{ groups['aap'] + groups['rhel_web'] }}" # Loop through your internal Linux host groups
      delegate_to: jump-host # This task runs on the Jump Host itself
      become: true # May need root to add to /etc/ssh/ssh_known_hosts, or just user's
      run_once: true # Ensure the known_hosts lookup happens only once for each host
      when: groups['aap'] is defined or groups['rhel_web'] is defined # Only run if groups exist
