---
# ─────────────────────────────────────────────────────────────
# Playbook: install-aap.yml
# Purpose : Copy bundle from jump → AAP VM, unpack, run setup.sh
# ─────────────────────────────────────────────────────────────

- name: Install Ansible Automation Platform
  hosts: aap
  become: true

  roles:
    - aap_install
