---
# ─────────────────────────────────────────────────────────────
# Playbook : install-aap.yml           (run FROM the jump-host)
# Purpose  : Unpack the disconnected bundle on the jump-host
#            and execute setup.sh against the target AAP node.
# ─────────────────────────────────────────────────────────────

- name: Install Ansible Automation Platform FROM jump-host
  hosts: jump
  gather_facts: false
  become: true           # needed to write under /opt

  roles:
    - run_aap_installer_from_jump
