# ─────────────────────────────────────────────────────────────
# Playbook: post-provision.yml
# Purpose : Orchestrate jump-host prep, bundle upload, repo clone,
#           SSH bootstrap, and disk provisioning for the AAP host.
# ─────────────────────────────────────────────────────────────

- name: Post-Provisioning Automation on Jump Host
  hosts: jump
  gather_facts: false
  vars:
    ansible_user_dir: /home/rheluser
    private_key_path: "{{ private_key_path }}"
    repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    target_dir: "{{ ansible_user_dir }}/{{ repo_url | basename | regex_replace('\\.git$', '') }}"
    jump_host_inventory_path: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/inventory/demo-hosts"
  tasks: []


# ─────────────────────────────────────────────────────
# Step 0 – Configure jump host (packages, ruamel.yaml, etc.)
# ─────────────────────────────────────────────────────
- name: Step 0 – Configure the Jump Host
  import_playbook: configure-jump-host.yml


# ─────────────────────────────────────────────────────
# Step 1 – Upload AAP bundle to jump host
# ─────────────────────────────────────────────────────
- name: Step 1 – Upload AAP Disconnected Installer
  import_playbook: upload-aap-installer.yml

# ─────────────────────────────────────────────────────
# Step 2 – Clone project repo to jump host
# ─────────────────────────────────────────────────────
- name: Step 2 – Clone Git Repository
  import_playbook: clone-repo-to-jump.yml

# ─────────────────────────────────────────────────────
# Step 3 – Bootstrap SSH connectivity jump → AAP host
#           (includes key copy, known_hosts, test)
# ─────────────────────────────────────────────────────
- name: Step 3 – Bootstrap SSH Connectivity
  import_playbook: bootstrap-ssh.yml
  vars:
    aap_host_ip: "10.0.1.12"
    aap_target_user: "rheluser"
    aap_target_ssh_key: "{{ private_key_path }}"
    aap_port: 22                       # change if non-default
    # the merged bootstrap playbook handles everything else

# ─────────────────────────────────────────────────────
# Step 4 – Trigger AAP Disk Resize (run from jump host)
# ─────────────────────────────────────────────────────
- name: Step 4 – Resize AAP Disk from Jump Host
  hosts: jump
  gather_facts: false
  vars:
    ansible_user_dir: /home/rheluser
    jump_host_inventory_path: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/inventory/demo-hosts"

  tasks:
    - name: Run resize-disks-aap.yml via the jump-host’s own Ansible
      ansible.builtin.shell: |
        export ANSIBLE_CONFIG="{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/ansible.cfg"
        {{ ansible_user_dir }}/.local/bin/ansible-playbook \
          -i "{{ jump_host_inventory_path }}" \
          "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks/resize-disks-aap.yml"
      args:
        chdir: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks"
      register: resize_log
      changed_when: false

    - name: Show nested playbook output
      ansible.builtin.debug:
        var: resize_log.stdout_lines
