---
# ─────────────────────────────────────────────────────────────
# Playbook: post-provision.yml
# Purpose : Orchestrate jump-host prep, bundle upload, repo clone,
#           and disk provisioning for the AAP host.
# ─────────────────────────────────────────────────────────────

- name: Post-Provisioning Automation on Jump Host
  hosts: jump
  gather_facts: false
  vars:
    ansible_user_dir: /home/rheluser
    private_key_path: "{{ private_key_path }}"
    repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    target_dir: "{{ ansible_user_dir }}/{{ repo_url | basename | regex_replace('\\.git$', '') }}"
    jump_host_inventory_path: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/inventory/demo-hosts"

  tasks: []

# ─────────────────────────────────────────────────────
# Step 0 – SSH key and known_hosts management on Jump Host
# ─────────────────────────────────────────────────────
- name: Step 0 – Inject SSH Private Key and Manage Known Hosts on Jump Host
  import_playbook: copy-private-key.yml
  vars:
    private_key_path: "{{ private_key_path }}"
    aap_host_ip: "10.0.1.12"

# ─────────────────────────────────────────────────────
# Step 1 – Configure jump host (packages, ruamel.yaml, etc.)
# ─────────────────────────────────────────────────────
- name: Step 1 – Configure the Jump Host
  import_playbook: configure-jump-host.yml

# ─────────────────────────────────────────────────────
# Step 2 – Upload AAP bundle to jump host
# ─────────────────────────────────────────────────────
- name: Step 2 – Upload AAP Disconnected Installer
  import_playbook: upload-aap-installer.yml

# ─────────────────────────────────────────────────────
# Step 3 – Clone project repo to jump host
# ─────────────────────────────────────────────────────
- name: Step 3 – Clone Git Repository
  import_playbook: clone-repo-to-jump.yml

# ─────────────────────────────────────────────────────
# Step 4 – Trigger AAP Disk Resize (run from jump host)
# ─────────────────────────────────────────────────────
- name: Step 4 – Resize AAP Disk from Jump Host
  hosts: jump
  gather_facts: false

  tasks:
    - name: Debug Ansible configuration and SSH for inner playbook
      ansible.builtin.shell: |
        # Change directory to ensure relative paths are correct
        cd "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks"

        # Display the loaded ANSIBLE_CONFIG path
        echo "ANSIBLE_CONFIG environment variable: $ANSIBLE_CONFIG"

        # Verify if the config file exists and its content
        echo "Content of $ANSIBLE_CONFIG:"
        cat "$ANSIBLE_CONFIG"

        # Run ansible --version with the intended config
        echo "Ansible --version output with specified config:"
        ANSIBLE_CONFIG="$ANSIBLE_CONFIG" {{ ansible_user_dir }}/.local/bin/ansible --version

        # Attempt a direct SSH connection using Ansible's internal SSH client simulation (best effort)
        # This is not ansible-playbook, but a test to see if general SSH args are being picked up
        echo "Attempting a simulated SSH connection from Ansible CLI:"
        ANSIBLE_CONFIG="$ANSIBLE_CONFIG" {{ ansible_user_dir }}/.local/bin/ansible aap-host -i "{{ jump_host_inventory_path }}" -m ping -vvv
      register: debug_output_inner_env
      changed_when: false
      failed_when: false # Allow it to fail so we see the output

    - name: Display inner Ansible environment debug
      ansible.builtin.debug:
        var: debug_output_inner_env.stdout_lines

    - name: Run resize-disks-aap.yml from the jump host
      ansible.builtin.shell: |
        export ANSIBLE_CONFIG="{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/ansible.cfg"
        {{ ansible_user_dir }}/.local/bin/ansible-playbook \
          -i "{{ jump_host_inventory_path }}" \
          "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks/resize-disks-aap.yml"
      args:
        chdir: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks"
      changed_when: false
