---
# ─────────────────────────────────────────────────────────────
# Playbook: post-provision.yml
# Purpose : Orchestrate jump-host prep, bundle upload, repo clone,
#           and disk provisioning for the AAP host.
# ─────────────────────────────────────────────────────────────

- name: Post-Provisioning Automation on Jump Host
  # This targets the jump host from your laptop.
  # The inventory for *this* playbook needs to define 'jump-host' with its public IP.
  # Let's assume your 'demo-hosts' file correctly reflects the public IP for 'jump-host'
  # if you're running this from your laptop using that inventory.
  # If 'jump-host' in demo-hosts is its *private* IP, you'll need a separate inventory for local runs.
  # For now, let's assume demo-hosts used locally has jump-host public IP.
  hosts: jump
  gather_facts: false
  vars:
    ansible_user_dir: /home/rheluser
    private_key_path: "{{ private_key_path }}" # Path on your laptop
    repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    target_dir: "{{ ansible_user_dir }}/{{ repo_url | basename | regex_replace('\\.git$', '') }}"

  tasks: [] # Keep this empty, tasks are imported

# ─────────────────────────────────────────────────────
# Step 0 – SSH key and known_hosts management on Jump Host
# ─────────────────────────────────────────────────────
- name: Step 0 – Inject SSH Private Key and Manage Known Hosts on Jump Host
  import_playbook: copy-private-key.yml
  vars:
    private_key_path: "{{ private_key_path }}"
    # Pass the IP of the AAP host so copy-private-key can keyscan it
    aap_host_ip: "10.0.1.12"
    # Pass the IP of the jump host's *private* IP if copy-private-key needs it for some reason
    # (Unlikely, but for completeness)
    jump_host_internal_ip: "10.0.1.10"
    # Specify the common SSH args here to ensure consistency
    common_ssh_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"


# ─────────────────────────────────────────────────────
# Step 1 – Configure jump host (packages, ruamel.yaml, etc.)
# ─────────────────────────────────────────────────────
- name: Step 1 – Configure the Jump Host
  import_playbook: configure-jump-host.yml

# ─────────────────────────────────────────────────────
# Step 2 – Upload AAP bundle to jump host
# ─────────────────────────────────────────────────────
- name: Step 2 – Upload AAP Disconnected Installer
  import_playbook: upload-aap-installer.yml

# ─────────────────────────────────────────────────────
# Step 3 – Clone project repo to jump host
# ─────────────────────────────────────────────────────
- name: Step 3 – Clone Git Repository
  import_playbook: clone-repo-to-jump.yml

# ─────────────────────────────────────────────────────
# Step 4 – Trigger AAP Disk Resize (run from jump host)
# ─────────────────────────────────────────────────────
- name: Step 4 – Resize AAP Disk from Jump Host
  hosts: jump
  gather_facts: false
  vars:
    ansible_user_dir: /home/rheluser
    jump_host_inventory_path: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/inventory/demo-hosts"
    jump_host_private_key_path: "{{ ansible_user_dir }}/.ssh/ansible-demo-key"

  tasks:
    - name: Run resize-disks-aap.yml from the jump host
      ansible.builtin.shell: |
        export ANSIBLE_CONFIG="{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/ansible.cfg"
        {{ ansible_user_dir }}/.local/bin/ansible-playbook \
          -i "{{ jump_host_inventory_path }}" \
          "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks/resize-disks-aap.yml" \
          -e "ansible_ssh_private_key_file={{ jump_host_private_key_path }}" \
          -e "ansible_user=rheluser" \
          -e "ansible_python_interpreter=/usr/bin/python3" \
          -e "ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null'" # <--- Critical line for auto-accept
      args:
        chdir: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks"
      changed_when: false
