---
# ─────────────────────────────────────────────────────────────
# Playbook: post-provision.yml
# Purpose : Orchestrate jump-host prep, bundle upload, repo clone
#           (AAP install happens later when you run install-aap.yml)
# ─────────────────────────────────────────────────────────────

- name: Post-Provisioning Automation on Jump Host
  hosts: jump
  gather_facts: false
  vars:
    target_dir: "{{ ansible_user_dir }}/{{ repo_url | basename | regex_replace('\\.git$', '') }}"
    private_key_path: "{{ private_key_path }}"

# Step 0 – SSH key
- name: Step 0 – Inject SSH Private Key to Jump Host
  import_playbook: copy-private-key.yml
  vars:
    private_key_path: "{{ private_key_path }}"

# Step 1 – Configure jump host (packages, ruamel.yaml, etc.)
- name: Step 1 – Configure the Jump Host
  import_playbook: ansible/playbooks/configure-jump-host.yml

# Step 2 – Upload AAP bundle to jump host
- name: Step 2 – Upload AAP Disconnected Installer
  import_playbook: ansible/playbooks/upload-aap-installer.yml

# Step 3 – Clone project repo to jump host
- name: Step 3 – Clone Git Repository
  import_playbook: clone-repo-to-jump.yml
