---
# ─────────────────────────────────────────────────────────────
# Playbook: post-provision.yml
# Purpose : Orchestrate jump-host prep, bundle upload, repo clone,
#           and disk provisioning for the AAP host.
# ─────────────────────────────────────────────────────────────

- name: Post-Provisioning Automation on Jump Host
  hosts: jump
  gather_facts: false
  vars:
    ansible_user_dir: /home/rheluser
    private_key_path: "{{ private_key_path }}"
    repo_url: "https://github.com/Deim0s13/ansible-cert-renewal-demo.git"
    target_dir: "{{ ansible_user_dir }}/{{ repo_url | basename | regex_replace('\\.git$', '') }}"

# ─────────────────────────────────────────────────────
# Step 0 – SSH key
# ─────────────────────────────────────────────────────
- name: Step 0 – Inject SSH Private Key to Jump Host
  import_playbook: copy-private-key.yml
  vars:
    private_key_path: "{{ private_key_path }}"

# ─────────────────────────────────────────────────────
# Step 1 – Configure jump host (packages, ruamel.yaml, etc.)
# ─────────────────────────────────────────────────────
- name: Step 1 – Configure the Jump Host
  import_playbook: configure-jump-host.yml

# ─────────────────────────────────────────────────────
# Step 2 – Upload AAP bundle to jump host
# ─────────────────────────────────────────────────────
- name: Step 2 – Upload AAP Disconnected Installer
  import_playbook: upload-aap-installer.yml

# ─────────────────────────────────────────────────────
# Step 3 – Clone project repo to jump host
# ─────────────────────────────────────────────────────
- name: Step 3 – Clone Git Repository
  import_playbook: clone-repo-to-jump.yml

# ─────────────────────────────────────────────────────
# Step 4 – Trigger AAP Disk Resize (run from jump host)
# ─────────────────────────────────────────────────────
- name: Step 4 – Resize AAP Disk from Jump Host
  hosts: jump
  gather_facts: false
  tasks:
    - name: Run resize-disks-aap.yml from the jump host
      ansible.builtin.command:
        cmd: >
          ansible-playbook -i {{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/inventory/provisioning-hosts
                           {{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks/resize-disks-aap.yml
      args:
        chdir: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/playbooks"
      environment:
        ANSIBLE_CONFIG: "{{ ansible_user_dir }}/ansible-cert-renewal-demo/ansible/ansible.cfg"
