---
- name: Resize and mount /opt on AAP node
  hosts: aap
  become: true
  gather_facts: false

  vars:
    opt_lv_size: 20g
    opt_mount_point: /opt
    opt_lv_name: optlv
    vg_name: rootvg

  tasks:

    # ─────────────────────────────────────────────────────
    # Step 0: Check available space in rootvg
    # ─────────────────────────────────────────────────────
    - name: Debug rootvg free space
      command: vgdisplay {{ vg_name }}
      register: vgdisplay_output
      changed_when: false

    - name: Print rootvg space
      debug:
        var: vgdisplay_output.stdout_lines

    # ─────────────────────────────────────────────────────
    # Step 1: Create Logical Volume for /opt
    # ─────────────────────────────────────────────────────
    - name: Create logical volume for /opt
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ opt_lv_name }}"
        size: "{{ opt_lv_size }}"
        state: present

    # ─────────────────────────────────────────────────────
    # This debug task is still helpful, as it will now show the actual
    # result of the lvol module without the spurious 'removes_backup' error.
    # We still want to see its output if the LV isn't being created.
    # ─────────────────────────────────────────────────────
    - name: Print LV creation result (full output for debugging)
      debug:
        var: create_lv_result
        verbosity: 1 # Keep this if you're running with -vvv

    # ─────────────────────────────────────────────────────
    # Step 2: Format the LV with XFS
    # ─────────────────────────────────────────────────────
    - name: Create filesystem on the new logical volume
      filesystem:
        fstype: xfs
        dev: "/dev/{{ vg_name }}/{{ opt_lv_name }}"
      when: create_lv_result.changed and ('lv_name' in create_lv_result and create_lv_result.lv_name == opt_lv_name)

    # ─────────────────────────────────────────────────────
    # Step 3: Ensure /opt Exists
    # ─────────────────────────────────────────────────────
    - name: Ensure /opt directory exists
      file:
        path: "{{ opt_mount_point }}"
        state: directory

    # ─────────────────────────────────────────────────────
    # Step 4: Mount /opt
    # ─────────────────────────────────────────────────────
    - name: Mount /opt
      mount:
        path: "{{ opt_mount_point }}"
        src: "/dev/{{ vg_name }}/{{ opt_lv_name }}"
        fstype: xfs
        opts: defaults
        state: mounted
      # Only attempt to mount if the LV was created and formatted
      when: create_lv_result.changed and ('lv_name' in create_lv_result and create_lv_result.lv_name == opt_lv_name)

    # ─────────────────────────────────────────────────────
    # Step 5: Persist /opt Mount in fstab
    # ─────────────────────────────────────────────────────
    - name: Make /opt mount persistent
      mount:
        path: "{{ opt_mount_point }}"
        src: "/dev/{{ vg_name }}/{{ opt_lv_name }}"
        fstype: xfs
        opts: defaults
        state: present
      # Only persist if the LV was created and formatted
      when: create_lv_result.changed and ('lv_name' in create_lv_result and create_lv_result.lv_name == opt_lv_name)


    # ─────────────────────────────────────────────────────
    # Step 6: Confirm mount success
    # ─────────────────────────────────────────────────────
    - name: Check mount target
      command: mountpoint {{ opt_mount_point }}
      register: mountpoint_check
      failed_when: mountpoint_check.rc != 0
      changed_when: false
      # Only check if the mount was attempted
      when: create_lv_result.changed and ('lv_name' in create_lv_result and create_lv_result.lv_name == opt_lv_name)
