---
# ─────────────────────────────────────────────────────────────
# Playbook: resize-disks-aap.yml
# Purpose : Extend rootvg and mount /opt for AAP installer use
# Target  : AAP node
# ─────────────────────────────────────────────────────────────

- name: Resize and mount /opt on AAP node
  hosts: aap
  become: true
  gather_facts: false

  vars:
    pv_device: /dev/sdb
    vg_name: rootvg
    opt_lv_name: optlv
    opt_lv_size: 20g
    opt_mount_point: /opt

  tasks:

    # ─────────────────────────────────────────────────────
    # Step 1: Prepare /dev/sdb and Extend rootvg
    # ─────────────────────────────────────────────────────
    - name: Ensure /dev/sdb is not mounted
      mount:
        path: /mnt
        state: absent
      ignore_errors: true  # In case not mounted

    - name: Wipe existing filesystem on /dev/sdb (destructive!)
      command: "wipefs -a {{ pv_device }}"
      when: pv_device is defined

    - name: Extend rootvg with /dev/sdb
      community.general.lvg:
        vg: "{{ vg_name }}"
        pvs: "{{ pv_device }}"
        pesize: 4M
        state: present

    # ─────────────────────────────────────────────────────
    # Step 2: Create Logical Volume for /opt
    # ─────────────────────────────────────────────────────
    - name: Create logical volume for /opt
      community.general.lvol:
        vg: "{{ vg_name }}"
        lv: "{{ opt_lv_name }}"
        size: "{{ opt_lv_size }}"
        state: present

    # ─────────────────────────────────────────────────────
    # Step 3: Format the LV with XFS
    # ─────────────────────────────────────────────────────
    - name: Create filesystem on the new logical volume
      filesystem:
        fstype: xfs
        dev: "/dev/{{ vg_name }}/{{ opt_lv_name }}"

    # ─────────────────────────────────────────────────────
    # Step 4: Ensure /opt Exists
    # ─────────────────────────────────────────────────────
    - name: Ensure /opt directory exists
      file:
        path: "{{ opt_mount_point }}"
        state: directory

    # ─────────────────────────────────────────────────────
    # Step 5: Mount /opt
    # ─────────────────────────────────────────────────────
    - name: Mount /opt
      mount:
        path: "{{ opt_mount_point }}"
        src: "/dev/{{ vg_name }}/{{ opt_lv_name }}"
        fstype: xfs
        opts: defaults
        state: mounted

    # ─────────────────────────────────────────────────────
    # Step 6: Persist /opt Mount in fstab
    # ─────────────────────────────────────────────────────
    - name: Make /opt mount persistent
      mount:
        path: "{{ opt_mount_point }}"
        src: "/dev/{{ vg_name }}/{{ opt_lv_name }}"
        fstype: xfs
        opts: defaults
        state: present
