---
- name: Resize and mount /opt on AAP node
  hosts: aap
  gather_facts: false

  vars:
    # Connection variables (passed via -e, so these defaults are backup)
    ansible_host: "{{ aap_ip | default('10.0.1.12') }}"
    ansible_port: "{{ aap_port | default('22') }}"
    ansible_user: "{{ aap_target_user | default('rheluser') }}"
    ansible_ssh_private_key_file: "{{ aap_target_ssh_key | default('/home/rheluser/.ssh/ansible-demo-key') }}"
    ansible_python_interpreter: "/usr/bin/python3"

    # Define the LVM/mount variables here:
    vg_name: "rootvg"
    opt_lv_name: "optlv"
    opt_lv_size: "50g"
    opt_mount_point: "/opt"

  tasks:

    # ─────────────────────────────────────────────────────
    # Step 0: Debug connection variables
    # ─────────────────────────────────────────────────────

    - name: Debug connection variables for aap-host
      ansible.builtin.debug:
        msg: "Connecting to {{ ansible_host }}:{{ ansible_port }} as {{ ansible_user }} using key {{ ansible_ssh_private_key_file }}"

    # ─────────────────────────────────────────────────────
    # Step 1: Check available space in rootvg
    # ─────────────────────────────────────────────────────
    - name: Debug rootvg free space
      command: vgdisplay {{ vg_name }}
      register: vgdisplay_output
      changed_when: false

    - name: Print rootvg space
      debug:
        var: vgdisplay_output.stdout_lines

    # ─────────────────────────────────────────────────────
    # Step 2: Create Logical Volume for /opt
    # ─────────────────────────────────────────────────────
    - name: Create logical volume for /opt
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ opt_lv_name }}"
        size: "{{ opt_lv_size }}"
        state: present
      register: create_lv_result
      ignore_errors: false

    # ─────────────────────────────────────────────────────
    # NEW STEP: Verify if the LV actually exists after the lvol task.
    # This will be the definitive check for subsequent 'when' conditions.
    # ─────────────────────────────────────────────────────
    - name: Verify optlv exists after creation attempt
      command: "lvdisplay /dev/{{ vg_name }}/{{ opt_lv_name }}"
      register: lv_exist_check
      failed_when: lv_exist_check.rc != 0
      changed_when: false

    # ─────────────────────────────────────────────────────
    # Step 2.5 (moved the debug after the existence check)
    # ─────────────────────────────────────────────────────
    - name: Print LV creation result (full output for debugging)
      debug:
        var: create_lv_result
        verbosity: 1 # Keep this to see the output with -vvv

    # ─────────────────────────────────────────────────────
    # Step 3: Format the LV with XFS
    # ─────────────────────────────────────────────────────
    - name: Create filesystem on the new logical volume
      filesystem:
        fstype: xfs
        dev: "/dev/{{ vg_name }}/{{ opt_lv_name }}"
      when: lv_exist_check.rc == 0

    # ─────────────────────────────────────────────────────
    # Step 4: Ensure /opt Exists
    # ─────────────────────────────────────────────────────
    - name: Ensure /opt directory exists
      file:
        path: "{{ opt_mount_point }}"
        state: directory

    # ─────────────────────────────────────────────────────
    # Step 5: Mount /opt
    # ─────────────────────────────────────────────────────
    - name: Mount /opt
      mount:
        path: "{{ opt_mount_point }}"
        src: "/dev/{{ vg_name }}/{{ opt_lv_name }}"
        fstype: xfs
        opts: defaults
        state: mounted
      # Only attempt to mount if the LV verification task succeeded.
      when: lv_exist_check.rc == 0

    # ─────────────────────────────────────────────────────
    # Step 6: Persist /opt Mount in fstab
    # ─────────────────────────────────────────────────────
    - name: Make /opt mount persistent
      mount:
        path: "{{ opt_mount_point }}"
        src: "/dev/{{ vg_name }}/{{ opt_lv_name }}"
        fstype: xfs
        opts: defaults
        state: present
      # Only persist if the LV verification task succeeded.
      when: lv_exist_check.rc == 0

    # ─────────────────────────────────────────────────────
    # Step 7: Confirm mount success
    # ─────────────────────────────────────────────────────
    - name: Check mount target
      command: mountpoint {{ opt_mount_point }}
      register: mountpoint_check
      failed_when: mountpoint_check.rc != 0
      changed_when: false
      # Only check if the mount was attempted.
      when: lv_exist_check.rc == 0
