---
# ─────────────────────────────────────────────────────────────
# Playbook : resize-disks-aap.yml
# Purpose  : Expand the existing /opt logical volume on the AAP
#            node **without** touching partitions or PVs.
#            ▸ No growpart ▸ No pvresize
#            ▸ Single lvol task with resizefs=true
# ─────────────────────────────────────────────────────────────
# Assumes  :
#   • /opt is   /dev/{{ vg_name }}/{{ lv_name }}
#   • VG has enough free space for {{ new_lv_size }}
#   • Filesystem on the LV is XFS
# ─────────────────────────────────────────────────────────────

- name: Resize /opt LV on AAP node
  hosts: aap
  gather_facts: false
  become: true

  vars:
    # ── LVM details ────────────────────────────────────────
    vg_name       : "rootvg"
    lv_name       : "optlv"
    new_lv_size   : "60g"      # ← Adjust as required
    mount_point   : "/opt"

  tasks:
    # ───────────────────────────────────────────────────────
    # Step 1 ▸ Show current space (informational)
    # ───────────────────────────────────────────────────────
    - name: Debug ▸ VG free space
      command: vgdisplay {{ vg_name }}
      register: vg_info
      changed_when: false

    - name: Debug ▸ LV size
      command: lvdisplay /dev/{{ vg_name }}/{{ lv_name }}
      register: lv_info
      changed_when: false

    - name: Report current sizes
      debug:
        msg:
          - "{{ (vg_info.stdout_lines | select('search','Free.*Size')).list }}"
          - "{{ (lv_info.stdout_lines | select('search','LV Size')).list }}"

    # ───────────────────────────────────────────────────────
    # Step 2 ▸ Extend LV + grow filesystem (one-shot)
    # ───────────────────────────────────────────────────────
    - name: Extend {{ lv_name }} to {{ new_lv_size }} and grow XFS
      community.general.lvol:
        vg       : "{{ vg_name }}"
        lv       : "{{ lv_name }}"
        size     : "{{ new_lv_size }}"
        resizefs : true       # auto-grows mounted FS
        state    : present

    # ───────────────────────────────────────────────────────
    # Step 3 ▸ Verify new capacity
    # ───────────────────────────────────────────────────────
    - name: Confirm /opt now larger
      command: df -h {{ mount_point }}
      register: df_opt
      changed_when: false

    - name: Show updated /opt usage
      debug:
        var: df_opt.stdout_lines
