# ─────────────────────────────────────────────────────────────
# Playbook: deploy-ssh-keys.yml
# Purpose: Copy SSH public/private keys to Linux VMs (excluding jump host)
# ─────────────────────────────────────────────────────────────

- name: Deploy SSH Keys to Linux Hosts
  hosts: linux:!jump
  become: true
  vars:
    ssh_key_path: "/home/rheluser/.ssh/ansible-demo-key"
    ssh_pub_key_path: "/home/rheluser/.ssh/ansible-demo-key.pub"
    ssh_user: "rheluser"

  tasks:

    # ─────────────────────────────────────────────────────────
    # Step 1: Ensure .ssh directory exists
    # ─────────────────────────────────────────────────────────
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ ssh_user }}/.ssh"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0700'

    # ─────────────────────────────────────────────────────────
    # Step 2: Deploy SSH public key
    # ─────────────────────────────────────────────────────────
    - name: Deploy SSH public key
      copy:
        src: "{{ ssh_pub_key_path }}"
        dest: "/home/{{ ssh_user }}/.ssh/authorized_keys"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0600'

    # ─────────────────────────────────────────────────────────
    # Step 3: Optionally deploy SSH private key
    # ─────────────────────────────────────────────────────────
    - name: Optionally deploy SSH private key (if needed)
      copy:
        src: "{{ ssh_key_path }}"
        dest: "/home/{{ ssh_user }}/.ssh/ansible-demo-key"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0600'
      when: ssh_key_path is defined
