# ─────────────────────────────────────────────────────────────
# Playbook: setup-ssh-access.yml
# Purpose: Set up SSH access for passwordless automation
#          from the Jump Host to all Linux nodes
# ─────────────────────────────────────────────────────────────

# ─────────────────────────────────────────────────────────────
# Step 1: Copy SSH private/public keys to the Jump Host
# ─────────────────────────────────────────────────────────────
- name: Copy SSH keys to Jump Host
  hosts: jump
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    # ─────────────────────────────────────────────────────────
    # Ensure .ssh directory exists
    # ─────────────────────────────────────────────────────────
    - name: Ensure .ssh directory exists
      file:
        path: /home/rheluser/.ssh
        state: directory
        owner: rheluser
        group: rheluser
        mode: '0700'

    # ─────────────────────────────────────────────────────────
    # Copy SSH private key to Jump Host
    # ─────────────────────────────────────────────────────────
    - name: Copy SSH private key
      copy:
        src: files/ansible-demo-key
        dest: /home/rheluser/.ssh/ansible-demo-key
        owner: rheluser
        group: rheluser
        mode: '0600'

    # ─────────────────────────────────────────────────────────
    # Copy SSH public key to Jump Host
    # ─────────────────────────────────────────────────────────
    - name: Copy SSH public key
      copy:
        src: files/ansible-demo-key.pub
        dest: /home/rheluser/.ssh/ansible-demo-key.pub
        owner: rheluser
        group: rheluser
        mode: '0644'

# ─────────────────────────────────────────────────────────────
# Step 2: Add public key to all Linux nodes' authorized_keys
# ─────────────────────────────────────────────────────────────
- name: Authorize SSH key on all Linux hosts
  hosts: linux
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    # ─────────────────────────────────────────────────────────
    # Ensure .ssh directory exists
    # ─────────────────────────────────────────────────────────
    - name: Ensure .ssh directory exists
      file:
        path: /home/rheluser/.ssh
        state: directory
        owner: rheluser
        group: rheluser
        mode: '0700'

    # ─────────────────────────────────────────────────────────
    # Add Jump Host's public key to authorized_keys
    # ─────────────────────────────────────────────────────────
    - name: Add public key to authorized_keys
      authorized_key:
        user: rheluser
        key: "{{ lookup('file', 'files/ansible-demo-key.pub') }}"
        state: present
