# Non‑sensitive defaults for the AAP‑install role.
aap_bundle_src: "/var/tmp/aap-setup-2.5.tar.gz" # on jump‑host
aap_bundle_dest: "/var/opt/aap-setup-2.5.tar.gz" # on AAP VM
aap_setup_dir: "/var/opt/ansible-automation-platform-setup"

aap_registry_url: registry.redhat.io
aap_admin_password: "{{ lookup('env','AAP_ADMIN_PASSWORD') | default('', true) }}"
aap_pg_password: "{{ lookup('env','AAP_PG_PASSWORD')   | default('', true) }}"
